apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-prometheus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /prometheus
        backend:
          serviceName: monitoring-prometheus
          servicePort: 9090
