apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: security-api-v1
  namespace: ucvelocity
  labels:
    app: security-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-api
  template:
    metadata:
      labels:
        app: security-api
    spec:
      containers:
      - name: security-api
        image: heatherzh/log-test:v1
        env:
          - name: "LOGGER_ES_URL"
            value: "http://9.42.27.10:30148/_bulk"
          - name: "LOGGER_CHANNEL"
            value: "security-api"
        ports:
        - containerPort: 3000
          name: ui
          protocol: TCP
