apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: ucvelocity
  labels:
    component: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        env:
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx2g
        - name: bootstrap.memory_lock
          value: "true"
        - name: http.host
          value: 0.0.0.0
        - name: transport.host
          value: 127.0.0.1
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
