apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: default
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: "docker.elastic.co/kibana/kibana:6.2.3"
        env:
        # Important that the IP address is changed to the Elastic Search client service clusterIP
        - name: ELASTICSEARCH_URL
          value: 'http://x.x.x.x:9200'
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
